version: '3.8'

services:
 
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
      
    environment:
      - MONGO_URL=mongodb://mongodb:27017/vibe
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
      - backend

volumes:
  mongo_data:
