version: "3.8"

services:
    mongo:
        image: mongo:6
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - "27017:27017"

    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ENABLE_ADMIN: true
            ME_CONFIG_MONGODB_AUTH_DATABASE: admin  
            ME_CONFIG_MONGODB_AUTH_USERNAME: admin
            ME_CONFIG_MONGODB_AUTH_PASSWORD: password
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
        depends_on:
            - mongo
        ports:
          - "8888:8081"