version: "3.8"

services:
    mongo:
        image: mongo:6
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - "27017:27017"

    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ENABLE_ADMIN: true
            ME_CONFIG_MONGODB_AUTH_DATABASE: admin  
            ME_CONFIG_MONGODB_AUTH_USERNAME: admin
            ME_CONFIG_MONGODB_AUTH_PASSWORD: password
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
        depends_on:
            - mongo
        ports:
          - "8888:8081"

    ollama:
        image: ollama/ollama
        ports:
          - "8078:8078"
        restart: unless-stopped

    open-webui:
        image: ghcr.io/open-webui/open-webui:main
        ports:
          - "8077:8080"
        environment:
          - OLLAMA_API_BASE_URL=http://ollama:8078
        depends_on:
          - ollama

    node-stream:
        build: ./node-stream
        ports:
          - "8079:8079"
        environment:
          MONGO_URL: mongodb://admin:password@mongo:27017/admin
        depends_on:
          - mongo