
services:
    mongo:
        image: mongo:6
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - "27017:27017"

    mongo-express:
        image: mongo-express
        environment:
            ME_CONFIG_MONGODB_SERVER: mongo
            ME_CONFIG_MONGODB_PORT: 27017
            ME_CONFIG_MONGODB_ENABLE_ADMIN: true
            ME_CONFIG_MONGODB_AUTH_DATABASE: admin  
            ME_CONFIG_MONGODB_AUTH_USERNAME: admin
            ME_CONFIG_MONGODB_AUTH_PASSWORD: password
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
        depends_on:
            - mongo
        ports:
          - "8081:8081"

    open-webui:
      image: ghcr.io/open-webui/open-webui:latest
      container_name: open-webui
      volumes:
      - open-webui:/app/backend/data
      pull_policy: always
      depends_on:
      - ollama
      ports:
      - 8080:8080
      environment: 
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=baby
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=123456
      extra_hosts:
      - host.docker.internal:host-gateway
      restart: unless-stopped
      networks:
      - ollama-docker   

    ollama:
      image: ollama/ollama:latest
      container_name: ollama
      ports:
      - 11434:11434
      volumes:
      - ollama:/root/.ollama
      pull_policy: always
      tty: true
      restart: always
      environment:
      - OLLAMA_KEEP_ALIVE=24h
      networks:
      - ollama-docker
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]

    node-stream:
        build: ./node-stream
        ports:
          - "8079:8079"
        environment:
          MONGO_URL: mongodb://admin:password@mongo:27017/admin
        depends_on:
          - mongo

networks:
  ollama-docker:
    driver: bridge  

volumes:
  ollama:
  open-webui:
  