version: "3.8"

services:
    mongo:
        image: mongo:6
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - "27017:27017"

    mongo-express:
        image: mongo-expres
        depends_on:
            - mongo
        ports:
          - "8888:8081"